title: George Saad
description: I'm a 3rd year Machine Intelligence major, Engineering Science student at the University of Toronto. I have extensive experience in software thorugh many projects and internships.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
markdown: kramdown
