title: George Saad
author: George Saad
description: Building AI to solve real-world problems. Specializing in <b>LLMs</b> and <b>Recommender Systems</b>.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
logo: assets/img/profile.jpg
collections:
  tags:
    output: true
    permalink: /tag/:name/

defaults:
  - scope:
      path: ""
      type: tags
    values:
      layout: tag

permalink: /:year/:month/:day/:title/