title: George Saad
description: I'm a 4th year Machine Intelligence major, Engineering Science student at the University of Toronto. I have extensive experience in software through many projects and internships.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
logo: assets/img/profile.png